# Generated by Django 2.2.17 on 2021-02-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20210204_1610'),
        ('rango', '0002_category_slug'),
    ]

    operations = [
    ]
